# Listado de nombres de empresas importantes en Estados Unidos

nombres_clientes = [
    "Apple Inc.",
    "Amazon.com Inc.",
    "Microsoft Corporation",
    "Alphabet Inc. (Google)",
    "Facebook Inc.",
    "Berkshire Hathaway Inc.",
    "Johnson & Johnson",
    "Visa Inc.",
    "JPMorgan Chase & Co.",
    "Walmart Inc.",
    "Procter & Gamble Co.",
    "Mastercard Incorporated",
    "UnitedHealth Group Incorporated",
    "Bank of America Corporation",
    "Intel Corporation",
    "Verizon Communications Inc.",
    "The Walt Disney Company",
    "Coca-Cola Company",
    "AT&T Inc.",
    "Cisco Systems Inc.",
    "Pfizer Inc.",
    "Nike Inc.",
    "Chevron Corporation",
    "McDonald's Corporation",
    "Adobe Inc.",
    "Salesforce.com Inc.",
    "Netflix Inc.",
    "Tesla Inc.",
    "Oracle Corporation",
    "IBM Corporation",
    "Exxon Mobil Corporation",
    "Home Depot Inc.",
    "3M Company",
    "Abbott Laboratories",
    "Goldman Sachs Group Inc.",
    "Caterpillar Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company",
    "Johnson & Johnson",
    "Pfizer Inc.",
    "Intel Corporation",
    "Walmart Inc.",
    "Tesla Inc.",
    "Exxon Mobil Corporation",
    "Oracle Corporation",
    "IBM Corporation",
    "Home Depot Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company",
    "Johnson & Johnson",
    "Pfizer Inc.",
    "Intel Corporation",
    "Walmart Inc.",
    "Tesla Inc.",
    "Exxon Mobil Corporation",
    "Oracle Corporation",
    "IBM Corporation",
    "Home Depot Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company",
    "Johnson & Johnson",
    "Pfizer Inc.",
    "Intel Corporation",
    "Walmart Inc.",
    "Tesla Inc.",
    "Exxon Mobil Corporation",
    "Oracle Corporation",
    "IBM Corporation",
    "Home Depot Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company",
    "Johnson & Johnson",
    "Pfizer Inc.",
    "Intel Corporation",
    "Walmart Inc.",
    "Tesla Inc.",
    "Exxon Mobil Corporation",
    "Oracle Corporation",
    "IBM Corporation",
    "Home Depot Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company",
    "Johnson & Johnson",
    "Pfizer Inc.",
    "Intel Corporation",
    "Walmart Inc.",
    "Tesla Inc.",
    "Exxon Mobil Corporation",
    "Oracle Corporation",
    "IBM Corporation",
    "Home Depot Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company",
    "Johnson & Johnson",
    "Pfizer Inc.",
    "Intel Corporation",
    "Walmart Inc.",
    "Tesla Inc.",
    "Exxon Mobil Corporation",
    "Oracle Corporation",
    "IBM Corporation",
    "Home Depot Inc.",
    "American Express Company",
    "Starbucks Corporation",
    "Walt Disney Company",
    "Boeing Company"
]
